### ISSUE TITLE
Sur la page d’accueil, afficher les promotions, seulement et seulement si il y en a

### ISSUE THREAD

**Issue by Axecibles-Dev** [GuillaumeFaidherbe/Axeci-Boutik#1]
Le cahier des charges prévoyait d'afficher les promotions sur la page d'accueil, seulement et seulement si il y en a. Cependant, j'ai eu beau mettre des produits en promo, le bloc n’apparaît pas.

De plus, j'ai un bloc "Populaire" qui apparaît alors qu'il n'est pas demandé.

**Comment by GuillaumeFaidherbe** [comment]
Bonjour,

Oui effectivement, j'ai dégreffé le bloc populaire au niveau de
displayHomeTab au niveau de Positions. Pour le bloc promotion, la promotion
doit être créée dans Catalogue -> Produit puis onglet "Prix" et il faut
ajouter une règle spécifique au produit (ci-joint screen regles.png),
ensuite le bloc apparaît bien que s'il y a un produit ( on peut le faire
via la configuration du bloc Promotions ), si le bloc ne s'affiche pas, il
faut vider les caches car ce bloc utilise de cache.

Pour preuve que le bloc promotions s'affiche bien avec les produits en
promos, je vous joins un screenshot (promo.png)

Merci
Bonne journée
Guillaume Faidhebre

Le mer. 2 déc. 2020 à 10:45, Axecibles Dev <notifications@github.com> a
écrit :

**Comment by Axecibles-Dev** [comment]
Bonjour Guillaume,

Ok pour moi en vidant le cache.
Pouvez-vous envoyer les modifs de BDD avec le module populaire dégreffé ?

**Comment by GuillaumeFaidherbe** [comment]
Voici le dump de la BDD, je l'ai aussi commit sur le projet sur git.

Cordialement,
Guillaume Faidherbe

Le mer. 2 déc. 2020 à 11:36, Axecibles Dev <notifications@github.com> a
écrit :

**Comment by Axecibles-Dev** [comment]
OK pour moi
