### ISSUE TITLE
Supprimer Mondial Relay

### ISSUE THREAD

**Issue by Axecibles-Dev** [GuillaumeFaidherbe/Axeci-Boutik#3]
Le CDC ne prévoit que deux transporteurs : "Retrait en magasin" et "Colissimo".
Supprimer Mondial Relay.

**Comment by GuillaumeFaidherbe** [comment]
Bonjour,

Effectivement, j'ai rajouter mondial relay pour pouvoir tester si la
condition si et seulement si le transporteur est colissimo alors on fait la
modification du poids, je l'ai laissé pour vos tests, je viens donc de le
supprimer, et j'ai recommit la BDD sur le projet git, c'est la même BDD que
pour le ticket 'Sur la page d’accueil, afficher les promotions, seulement
et seulement si il y en a (#1)' donc il n'y aura qu'un réimporter la BDD
une fois.

Cordialement,
Guillaume Faidherbe

Le mer. 2 déc. 2020 à 10:52, Axecibles Dev <notifications@github.com> a
écrit :

**Comment by Axecibles-Dev** [comment]
OK
