### ISSUE TITLE
Supprimer le cache du dépôt

### ISSUE THREAD

**Issue by Axecibles-Dev** [GuillaumeFaidherbe/Axeci-Boutik#7]
Peux-tu supprimer le cache du dépôt et l'ajouter dans le .gitignore pour les prochains commits ?

**Comment by GuillaumeFaidherbe** [comment]
C'est fait, effectivement, c'était inutile de le commit à chaque fois, je
sais qu'il faudrait aussi changer le gitignore pour enlever d'autres
fichiers comme les contenus ou encore les configs

Le mer. 2 déc. 2020 à 12:23, Axecibles Dev <notifications@github.com> a
écrit :
